<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Trivy Security Report</title>
  <style>
    body { font-family: Arial; background: #f7f7f7; }
    h1 { color: #2c3e50; }
    table { border-collapse: collapse; width: 100%; background: #fff; }
    th, td { border: 1px solid #ddd; padding: 8px; }
    th { background: #2c3e50; color: white; }
    tr:nth-child(even) { background: #f2f2f2; }
    .CRITICAL { color: red; font-weight: bold; }
    .HIGH { color: orange; font-weight: bold; }
  </style>
</head>
<body>
<h1>🔐 Trivy Security Scan Report</h1>
<p>Generated by Jenkins</p>
{{ range .Results }}
  <h2>Target: {{ .Target }}</h2>
  <table>
    <tr>
      <th>Package</th>
      <th>Vulnerability ID</th>
      <th>Severity</th>
      <th>Installed Version</th>
      <th>Fixed Version</th>
    </tr>
    {{ range .Vulnerabilities }}
    <tr>
      <td>{{ .PkgName }}</td>
      <td>{{ .VulnerabilityID }}</td>
      <td class="{{ .Severity }}">{{ .Severity }}</td>
      <td>{{ .InstalledVersion }}</td>
      <td>{{ .FixedVersion }}</td>
    </tr>
    {{ end }}
  </table>
{{ end }}
</body>
</html>
